name: CI for Kivy App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Укажите версию Python

      - name: Install buildozer
        run: pip install buildozer

      - name: Install Kivy
        run: pip install kivy

      - name: Build APK
        run: buildozer android debug # Запускает сборку APK

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: kivy-apk
          path: dist/appMgera-0.1-debug.apk
